project:
  type: website
  output-dir: docs

website:
  title: "Aza Tulepbergenov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
